#include QMK_KEYBOARD_H


#define _LAYER0 0
#define _LAYER1 1

enum custom_keycodes {
    LAYER0 = SAFE_RANGE,
    LAYER1,
};

 const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {

 [_LAYER0] = LAYOUT_5x6(QK_GESC, KC_1, KC_2, KC_3, KC_4, KC_5, KC_6, KC_7, KC_8, KC_9, KC_0, LGUI(KC_L), 
 KC_BSPC, KC_Q, KC_W, KC_F, KC_P, KC_B, KC_J, KC_L, KC_U, KC_Y, KC_SCLN, KC_CAPS, 
 KC_TAB, KC_A, KC_R, KC_S, KC_T, KC_G, KC_M, KC_N, KC_E, KC_I, KC_O, KC_QUOT, 
 KC_DEL, LGUI_T(KC_X), LCTL_T(KC_C), LALT_T(KC_D), KC_V, KC_Z, KC_K, KC_H, RALT_T(KC_COMM), RCTL_T(KC_DOT), RGUI_T(KC_SLSH), KC_BSLS, 
 KC_MINS, KC_EQL, KC_LBRC, KC_RBRC, 
 LT(1,KC_ENT), KC_LSFT, KC_SPC, LT(1,KC_BSPC), 
 LCTL(KC_V), LCTL(KC_C), KC_UP, KC_DOWN, 
 LCTL(KC_Z), LCTL(KC_Y), KC_LEFT, KC_RGHT),

[_LAYER1] = LAYOUT_5x6(KC_F1, KC_F2, KC_F3, KC_F4, KC_F5, KC_F6, KC_F7, KC_F8, KC_F9, KC_F10, KC_F11, KC_F12, 
KC_SPC, KC_LGUI, KC_HOME, KC_UP, KC_END, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, 
KC_TAB, KC_LCTL, KC_LEFT, KC_DOWN, KC_RGHT, KC_FIND, KC_NO, KC_NO, KC_VOLD, KC_VOLU, KC_NO, KC_NO, 
KC_PSCR, KC_LSFT, KC_PGUP, KC_NO, KC_PGDN, KC_NO, KC_NO, KC_NO, KC_MPLY, KC_MUTE, KC_NO, QK_BOOT, 
KC_INS, KC_DEL, KC_MPRV, KC_MNXT, 
KC_NO, KC_TRNS, KC_TRNS, KC_NO, 
KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, 
KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS) 

};